name: Build VelixFlow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libgl1-mesa-dev ninja-build

      - name: Restore FetchContent Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: fetchcontent-linux-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            fetchcontent-linux-

      - name: Clean Previous Build
        run: rm -rf build

      - name: Build PhysX
        run: ./scripts/build_physx_linux.sh

      - name: Configure and Build
        run: |
          cmake -S . -B build -G Ninja -DPHYSX_BUILD_TYPE=checked
          cmake --build build --config Debug

      - name: Install to Staging Dir
        run: cmake --install build --prefix staging

      - name: Create Archive
        run: tar -czvf VelixFlow-linux.tar.gz -C staging .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelixFlow-linux
          path: VelixFlow-linux.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore FetchContent Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: fetchcontent-windows-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            fetchcontent-windows-

      - name: Clean Previous Build
        shell: pwsh
        run: |
          if (Test-Path build) {
            Remove-Item -Recurse -Force build
          }

      - name: Build PhysX for Windows
        shell: cmd
        run: scripts\build_physx_windows.bat

      - name: Configure and Build
        run: |
          cmake -S . -B build -G Ninja -DPHYSX_BUILD_TYPE=checked
          cmake --build build --config Debug

      - name: Install to Staging Dir
        run: cmake --install build --prefix staging

      - name: Create Archive
        run: tar -czvf VelixFlow-windows.tar.gz -C staging .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelixFlow-windows
          path: VelixFlow-windows.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install cmake ninja

      - name: Restore FetchContent Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: fetchcontent-macos-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            fetchcontent-macos-

      - name: Clean Previous Build
        run: rm -rf build

      - name: Configure and Build
        run: |
          cmake -S . -B build -G Ninja -DVELIX_USE_PHYSX=OFF -DPHYSX_BUILD_TYPE=checked
          cmake --build build --config Debug

      - name: Install to Staging Dir
        run: cmake --install build --prefix staging

      - name: Create Archive
        run: tar -czvf VelixFlow-macos.tar.gz -C staging .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelixFlow-macos
          path: VelixFlow-macos.tar.gz
